# NumPy-Arrays vs. Python-Listen

In [159]:
import numpy as np
import time

In [32]:
size = 1000000

x = np.arange(size) # numpy-array zwischen 0-size mit Schrittgröße 1
y = list(range(size)) # Python Liste mit Elementen 0-size mit Schrittgröße 1

print(x[:10])
print(y[:10])

print(sum(x==y)) # Prüfen ob alle Elemente gleich sind



[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1000000


In [33]:
# Numpy Array: Quadrieren der Elemente 
start = time.time()
x_sq = np.square(x)
end = time.time()
print(end - start)
print(x_sq[:10])

0.0013811588287353516
[ 0  1  4  9 16 25 36 49 64 81]


In [43]:
# Power
a = np.arange(10)
print('a = ', a)
print('a^2 = ', a^2) # Bitweises XOR
x1 = 3 # Binär '11'
x2 = 2 # Binär '10'
print('x1^x2 = ', x1^x2) # Bitweises XOR: 1 XOR 1 = 0, 1 XOR 0 = 1, Ergebnis ist '01' in dezimalschreibeweise 1

print('square(a) = ', np.square(a))
print('a*a = ', a*a)
print('a**2 = ', a**2)



a =  [0 1 2 3 4 5 6 7 8 9]
a^2 =  [ 2  3  0  1  6  7  4  5 10 11]
x1^x2 =  1
square(a) =  [ 0  1  4  9 16 25 36 49 64 81]
a*a =  [ 0  1  4  9 16 25 36 49 64 81]
a**2 =  [ 0  1  4  9 16 25 36 49 64 81]


In [5]:
# List - Loop - Quadrieren der Elemente
y_sq = y
start = time.time()
for i in range(len(y)):
    y_sq[i] = y[i]**2
end = time.time()
print(end - start)

print(y_sq[:10])
print(sum(y_sq == x_sq))

0.07065582275390625
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
1000000


In [6]:
# List - Loop - List Comprehensions
start = time.time()
y_squared = [i ** 2 for i in y]
end = time.time()
print(end - start)

print(y_sq[:10])
print(sum(y_sq == x_sq))

0.04595470428466797
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
1000000


In [12]:
a = np.arange(100)
a = a.reshape(10,10)+1
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [20]:
print(a[[0,4,9],])
print(a[[0,4,-1],])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [26]:
print(a[1::2,[2,6]])

[[13 17]
 [33 37]
 [53 57]
 [73 77]
 [93 97]]


In [28]:
print(a[0:3,0:3])

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [29]:
a[[1,3],] = -a[[1,3],]
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [-11 -12 -13 -14 -15 -16 -17 -18 -19 -20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [-31 -32 -33 -34 -35 -36 -37 -38 -39 -40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [30]:
a[a<25] = 0
print(a)

[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  25  26  27  28  29  30]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


# Statistiken

In [103]:
np.random.seed(1)
niederschlag = np.random.randint(20, 150, size=(3, 12, 4))  # 3 Städte, 12 Monate, 4 Messungen pro Monat
print(niederschlag[0,:,:])
print(niederschlag[0,0,:])

[[ 57  92  99 149]
 [ 91  45  40 121]
 [ 70  88 116 106]
 [ 27  83  81  42]
 [ 77  21 148  80]
 [ 28 135 141  50]
 [ 91  69  77  23]
 [ 44  63  96  46]
 [ 72 100 129 135]
 [ 61  35  84  45]
 [131  46 124  42]
 [ 29 146  43 145]]
[ 57  92  99 149]


In [104]:
print(niederschlag)

[[[ 57  92  99 149]
  [ 91  45  40 121]
  [ 70  88 116 106]
  [ 27  83  81  42]
  [ 77  21 148  80]
  [ 28 135 141  50]
  [ 91  69  77  23]
  [ 44  63  96  46]
  [ 72 100 129 135]
  [ 61  35  84  45]
  [131  46 124  42]
  [ 29 146  43 145]]

 [[120  77 103  52]
  [ 30  43 107  45]
  [112  94  66  85]
  [133  97  23 148]
  [ 26  72  22  96]
  [ 27  97  95  96]
  [ 63  40  50  56]
  [123  27  65  77]
  [116  33  30  43]
  [144 101 141 114]
  [ 80 102 135 117]
  [123 118  30 116]]

 [[102  91  74  35]
  [ 40 138  42 134]
  [117 104  30 116]
  [ 81  76 116  45]
  [136  63  44  73]
  [ 89 121  41  60]
  [ 97 133  67  65]
  [107  65 136  86]
  [ 66 148  83  95]
  [ 55  53 103  68]
  [ 74  52  75  51]
  [ 48  94 129 119]]]


In [149]:
print('Minimum je Monat und Stadt: ', niederschlag.min(axis=2))
print(niederschlag.min(axis=2).shape)
print('Minimum je Stadt: ', np.min(np.min(niederschlag, axis=2), axis=1))
print('Minimum je Stadt: ', np.min(niederschlag, axis=(2,1)))
print('Mittelwert je Stadt: ', np.mean(niederschlag,axis=(2,1)))
print('Median je Stadt: ', np.median(niederschlag,axis=(2,1)))
print('Standardabweichung je Stadt: ', np.std(niederschlag, axis=(2,1)))

Minimum je Monat und Stadt:  [[ 57  40  70  27  21  28  23  44  72  35  42  29]
 [ 52  30  66  23  22  27  40  27  30 101  80  30]
 [ 35  40  30  45  44  41  65  65  66  53  51  48]]
(3, 12)
Minimum je Stadt:  [21 22 30]
Minimum je Stadt:  [21 22 30]
Mittelwert je Stadt:  [80.47916667 81.45833333 84.10416667]
Median je Stadt:  [78.5 89.5 78.5]
Standardabweichung je Stadt:  [38.4534294 37.7066298 32.0937686]


In [156]:
print('Maximaler Niederschlag [mm] = ', np.max(niederschlag, axis=(2,1)))
print('Stadt mit maximalem Niederschlag (Index): ', np.argmax(np.max(niederschlag, axis=(2,1))))

Maximaler Niederschlag [mm] =  [149 148 148]
Stadt mit maximalem Niederschlag (Index):  0


In [157]:
print('Mittelwert der Niederschlaege: ', np.mean(niederschlag, axis=(2,1)))
print('Maximaler Mittelwert (Index): ', np.argmax(np.mean(niederschlag, axis=(2,1))))

Mittelwert der Niederschlaege:  [80.47916667 81.45833333 84.10416667]
Maximaler Mittelwert (Index):  2


In [158]:
print('Standardabweichung der Niederschlaege: ', niederschlag.std(axis=(2,1)))
print('Maximum der Standardabweichung: ', np.max(np.std(niederschlag, axis=(2,1))))
print('Stadt mit maximalem Niederschlag: ',np.argmax(np.std(niederschlag, axis=(2,1))))

Standardabweichung der Niederschlaege:  [38.4534294 37.7066298 32.0937686]
Maximum der Standardabweichung:  38.45342940023541
Stadt mit maximalem Niederschlag:  0


In [145]:
print(np.mean(niederschlag, axis=2))
print(np.argmax(np.mean(niederschlag, axis=2), axis=1))

[[ 99.25  74.25  95.    58.25  81.5   88.5   65.    62.25 109.    56.25
   85.75  90.75]
 [ 88.    56.25  89.25 100.25  54.    78.75  52.25  73.    55.5  125.
  108.5   96.75]
 [ 75.5   88.5   91.75  79.5   79.    77.75  90.5   98.5   98.    69.75
   63.    97.5 ]]
[8 9 7]


In [150]:
# 1. Grundlegende statistische Kennzahlen für jede Stadt
min_niederschlag = np.min(niederschlag, axis=(1, 2))
max_niederschlag = np.max(niederschlag, axis=(1, 2))
mittelwert_niederschlag = np.mean(niederschlag, axis=(1, 2))
median_niederschlag = np.median(niederschlag, axis=(1, 2))

# 2. Vergleich der Städte
stadt_hoechster_durchschnitt = np.argmax(np.mean(niederschlag, axis=(1, 2)))
stadt_groesste_variabilitaet = np.argmax(np.std(niederschlag, axis=(1, 2)))

# 3. Erweiterte statistische Analysen
durchschnittlicher_monatlicher_niederschlag = np.mean(niederschlag, axis=2)
monat_hoechster_durchschnitt = np.argmax(np.mean(durchschnittlicher_monatlicher_niederschlag, axis=0))

min_niederschlag, max_niederschlag, mittelwert_niederschlag, median_niederschlag, stadt_hoechster_durchschnitt, stadt_groesste_variabilitaet, durchschnittlicher_monatlicher_niederschlag, monat_hoechster_durchschnitt

(array([21, 22, 30]),
 array([149, 148, 148]),
 array([80.47916667, 81.45833333, 84.10416667]),
 array([78.5, 89.5, 78.5]),
 2,
 0,
 array([[ 99.25,  74.25,  95.  ,  58.25,  81.5 ,  88.5 ,  65.  ,  62.25,
         109.  ,  56.25,  85.75,  90.75],
        [ 88.  ,  56.25,  89.25, 100.25,  54.  ,  78.75,  52.25,  73.  ,
          55.5 , 125.  , 108.5 ,  96.75],
        [ 75.5 ,  88.5 ,  91.75,  79.5 ,  79.  ,  77.75,  90.5 ,  98.5 ,
          98.  ,  69.75,  63.  ,  97.5 ]]),
 11)

In [155]:
print(np.mean(niederschlag, axis=(1)))
print(np.mean(niederschlag, axis=(2)))
print(np.mean(niederschlag, axis=(2,1)))
print(np.mean(niederschlag, axis=(1,2)))

[[64.83333333 76.91666667 98.16666667 82.        ]
 [91.41666667 75.08333333 72.25       87.08333333]
 [84.33333333 94.83333333 78.33333333 78.91666667]]
[[ 99.25  74.25  95.    58.25  81.5   88.5   65.    62.25 109.    56.25
   85.75  90.75]
 [ 88.    56.25  89.25 100.25  54.    78.75  52.25  73.    55.5  125.
  108.5   96.75]
 [ 75.5   88.5   91.75  79.5   79.    77.75  90.5   98.5   98.    69.75
   63.    97.5 ]]
[80.47916667 81.45833333 84.10416667]
[80.47916667 81.45833333 84.10416667]
