## The NumPy Array
Basierend auf Kyran Dale
https://github.com/Kyrand/dataviz-with-python-and-js-ed-2.git

In [140]:
import numpy as np

In [173]:
a = np.array([1, 2, 3]) # Horizontaler Vektor
a + a
a1 = np.array([[1], [2], [3]]) # Vertikaler Vektor

b = np.array([1,2,3,'text'])

print('a = ', a)
print('a1 = ', a1)
print('b = ',b)


a =  [1 2 3]
a1 =  [[1]
 [2]
 [3]]
b =  ['1' '2' '3' 'text']


In [142]:
def print_array_details(a):
    print('Dimensions: %d, shape: %s, dtype: %s'%(a.ndim, a.shape, a.dtype))

In [143]:
print_array_details(a)
print_array_details(a1)
print_array_details(b)

Dimensions: 1, shape: (3,), dtype: int64
Dimensions: 2, shape: (3, 1), dtype: int64
Dimensions: 1, shape: (4,), dtype: <U21


In [144]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Alternativ
a1 = np.array(list(range(1,10,1))) # range erzeugt Zahlen von 1 bis 10 mit Abstand 1
print('a1 = ', a1)

a1 =  [1 2 3 4 5 6 7 8 9]


In [145]:
print_array_details(a)

Dimensions: 1, shape: (8,), dtype: int64


In [146]:
a = a.reshape([2, 4])
print('a =', a)
print_array_details(a)

a = [[1 2 3 4]
 [5 6 7 8]]
Dimensions: 2, shape: (2, 4), dtype: int64


In [147]:
a = a.reshape([2, 2, 2])
print('a =', a)

a = [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [148]:
print_array_details(a)

Dimensions: 3, shape: (2, 2, 2), dtype: int64


In [149]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x.shape

(2, 3)

In [150]:
x.shape = (6,)
x

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [151]:
x = x.astype('int64')
x.dtype

dtype('int64')

## Creating Arrays

In [152]:
a = np.zeros([2,3])
print("a = ", a)
print(a.dtype)

a =  [[0. 0. 0.]
 [0. 0. 0.]]
float64


In [153]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [154]:
empty_array = np.empty((2,3))
print("empty_array = ", empty_array) # Die Werte des Arrays sind nicht-deterministisch
print(empty_array.dtype)

empty_array =  [[1. 1. 1.]
 [1. 1. 1.]]
float64


In [155]:
np.random.random((2,3)) # random: Random Sampling in numpy; random: Werte zwischen 0<=x<1

array([[0.98363628, 0.72996907, 0.29231454],
       [0.33205454, 0.01858337, 0.11788496]])

In [156]:
np.random.normal(0,1, (2,3)) # normal: Normalverteilung mit Mittelwert 0, Standardabweichung 1 und Shape (2,3)

array([[ 1.07656826,  0.43361681,  0.68488789],
       [-0.89807409,  1.4477989 , -0.29079983]])

In [157]:
a = np.linspace(2, 10, 5) # 5 numbers in range 2-10
print("a = ", a)
print(a.dtype)

a =  [ 2.  4.  6.  8. 10.]
float64


In [158]:
a = np.arange(2, 10, 2)
print("a = ", a)
print(a.dtype)

b = np.arange(2, 10, 2.)
print("b = ", b)
print(b.dtype)

a =  [2 4 6 8]
int64
b =  [2. 4. 6. 8.]
float64


## Array Indexing and Slicing

In [190]:
a = np.array([1, 2, 3, 4, 5, 6])
print("a[2] = ", a[2])


a[2] =  3


In [191]:
a[3:5]

array([4, 5])

In [192]:
# every second item from 0-4 set to 0
a[:4:2] = 0
a

array([0, 2, 0, 4, 5, 6])

In [193]:
a[::-1]

array([6, 5, 4, 0, 2, 0])

In [194]:
a = np.arange(16)
a = a.reshape(2,2,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [195]:
print(a[0])
print(np.array_equal(a[0,:,:], a[0]))
print(a[0,0,:])

[[0 1 2 3]
 [4 5 6 7]]
True
[0 1 2 3]


In [196]:
print(a[0,0,::2])

[0 2]


# Fancy Indexing

In [199]:
a = np.arange(10)
print('a = ', a)
i = np.array([2, 1, 8, 4]) # array aus indizes
a[i] = 99
print('a = ', a)

a =  [0 1 2 3 4 5 6 7 8 9]
a =  [ 0 99 99  3 99  5  6  7 99  9]


In [200]:
a[i] -= 10
print('a = ', a)

a =  [ 0 89 89  3 89  5  6  7 89  9]


In [204]:
# Auswahl Werte mit geradem Index ab 0
print('a = ', a[::2])

a =  [ 0 89 89  6 89]


In [205]:
# Boolsche Indexierung
print('a = ', a<10)

a =  [ True False False  True False  True  True  True False  True]


## A Few Basic Operations

In [206]:
a = np.arange(6)
a = a.reshape(2,3)
print('a = ', a)
print('a+2 = ', a+2)
print('a-2 = ', a-2)
print('a/2 = ', a/2.0)

a =  [[0 1 2]
 [3 4 5]]
a+2 =  [[2 3 4]
 [5 6 7]]
a-2 =  [[-2 -1  0]
 [ 1  2  3]]
a/2 =  [[0.  0.5 1. ]
 [1.5 2.  2.5]]


In [188]:
a = np.array([45, 65, 76, 32, 99, 22])
a < 50

array([ True, False, False,  True, False,  True])

In [212]:
# Some array methods
a = np.arange(8).reshape((2,4))
print('a = ', a)

# Minimum
print('a.min(axis=1) = ', a.min(axis=1))
# Summe
print('a.sum(axis=0) = ', a.sum(axis=0))
# Mittelwert
print('a.mean(axis=1) = ', a.mean(axis=1))
# Standardabweichung
print('a.std(axis=1) = ', a.std(axis=1))

a =  [[0 1 2 3]
 [4 5 6 7]]
a.min(axis=1) =  [0 4]
a.sum(axis=0) =  [ 4  6  8 10]
a.mean(axis=1) =  [1.5 5.5]
a.std(axis=1) =  [1.11803399 1.11803399]


In [89]:
# Trigonometric functions
pi = np.pi
a = np.array([pi, pi/2, pi/4, pi/6])
np.degrees(a) # radians to degrees

array([180.,  90.,  45.,  30.])

In [90]:
sin_a = np.sin(a)
sin_a

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 5.00000000e-01])

In [91]:
np.round(sin_a, 7) # round to 7 decimal places

array([0.       , 1.       , 0.7071068, 0.5      ])

In [92]:
# Sums, products, differences
a = np.arange(8).reshape((2,4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
np.cumsum(a, axis=1) # cumulative sum along second axis

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22]])

In [94]:
np.cumsum(a) # without axis argument, array is flattened

array([ 0,  1,  3,  6, 10, 15, 21, 28])

# Creating Array Functions

## Calculating a Moving Average

In [95]:
# Calculate a moving average with window size n
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [96]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [97]:
csum = np.cumsum(a)
csum

array([ 0,  1,  3,  6, 10, 15])

In [98]:
csum[3:] = csum[3:] - csum[:-3]
csum

array([ 0,  1,  3,  6,  9, 12])

In [99]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
moving_average(a, 4)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])